#!/usr/bin/env sh

./configure --prefix=/Users/ikarus/.opt \
  --enable-libffi \
  CFLAGS="-m64 -I/Users/ikarus/.opt64/include -I/Users/ikarus/.opt64/lib/libffi-3.0.6/include" \
  LDFLAGS="-m64 -L/Users/ikarus/.opt64/lib" \
&& make clean \
&& make

# LIBFFI configuration (on darwin):
#   ./configure 
#       --target=x86_64-darwin
#       --build=x86_64-darwin
#       --prefix=/Users/ikarus/.opt64
#       CFLAGS=-m64 
#       LDFLAGS=-m64
