#!/usr/bin/env sh

cp configure.64.ac configure.ac  && \
autoconf && \
./configure CFLAGS="-m64 -I/Users/ikarus/.opt64/include" \
  LDFLAGS="-m64 -L/Users/ikarus/.opt64/lib" \
&& make clean \
&& make

