/* automatically generated, do not edit */
#include "scheme.h"
#include <stdio.h>
ptr scheme_main(pcb_t* pcb){
extern void S_add_roots(pcb_t*,int*);
extern void S_check_roots(pcb_t*,int*);
extern void SL_values();
extern void SL_call_with_values();
extern void libsymboltable_entry(pcb_t*);
extern int libsymboltable_constant_count;
extern void libhandlers_entry(pcb_t*);
extern int libhandlers_constant_count;
extern void libcontrol_entry(pcb_t*);
extern int libcontrol_constant_count;
extern void libintelasm_entry(pcb_t*);
extern int libintelasm_constant_count;
extern void libcollect_entry(pcb_t*);
extern int libcollect_constant_count;
extern void librecord_entry(pcb_t*);
extern int librecord_constant_count;
extern void libcore_entry(pcb_t*);
extern int libcore_constant_count;
extern void libio_entry(pcb_t*);
extern int libio_constant_count;
extern void libwriter_entry(pcb_t*);
extern int libwriter_constant_count;
extern void libtokenizer_entry(pcb_t*);
extern int libtokenizer_constant_count;
extern void libexpand_entry(pcb_t*);
extern int libexpand_constant_count;
extern void libinterpret_entry(pcb_t*);
extern int libinterpret_constant_count;
extern void libcafe_entry(pcb_t*);
extern int libcafe_constant_count;
extern void libtrace_entry(pcb_t*);
extern int libtrace_constant_count;
extern void libposix_entry(pcb_t*);
extern int libposix_constant_count;
extern void libtoplevel_entry(pcb_t*);
extern void libcxr_entry(pcb_t*);
char** ap = (char**) pcb->allocation_pointer;
ap[0] = (char*) SL_values;
ap[1] = 0;
pcb->prim_208 = ((char*)ap) + closure_tag;
ap += 2;
ap[0] = (char*) SL_call_with_values;
ap[1] = 0;
pcb->prim_209 = ((char*)ap) + closure_tag;
ap += 2;
pcb->allocation_pointer = (char*)ap;
   S_add_roots(pcb, &libsymboltable_constant_count);
   libsymboltable_entry(pcb);
   S_check_roots(pcb, &libsymboltable_constant_count);
   S_add_roots(pcb, &libhandlers_constant_count);
   libhandlers_entry(pcb);
   S_check_roots(pcb, &libhandlers_constant_count);
   S_add_roots(pcb, &libcontrol_constant_count);
   libcontrol_entry(pcb);
   S_check_roots(pcb, &libcontrol_constant_count);
   S_add_roots(pcb, &libintelasm_constant_count);
   libintelasm_entry(pcb);
   S_check_roots(pcb, &libintelasm_constant_count);
   S_add_roots(pcb, &libcollect_constant_count);
   libcollect_entry(pcb);
   S_check_roots(pcb, &libcollect_constant_count);
   S_add_roots(pcb, &librecord_constant_count);
   librecord_entry(pcb);
   S_check_roots(pcb, &librecord_constant_count);
   S_add_roots(pcb, &libcore_constant_count);
   libcore_entry(pcb);
   S_check_roots(pcb, &libcore_constant_count);
   S_add_roots(pcb, &libio_constant_count);
   libio_entry(pcb);
   S_check_roots(pcb, &libio_constant_count);
   S_add_roots(pcb, &libwriter_constant_count);
   libwriter_entry(pcb);
   S_check_roots(pcb, &libwriter_constant_count);
   S_add_roots(pcb, &libtokenizer_constant_count);
   libtokenizer_entry(pcb);
   S_check_roots(pcb, &libtokenizer_constant_count);
   S_add_roots(pcb, &libexpand_constant_count);
   libexpand_entry(pcb);
   S_check_roots(pcb, &libexpand_constant_count);
   S_add_roots(pcb, &libinterpret_constant_count);
   libinterpret_entry(pcb);
   S_check_roots(pcb, &libinterpret_constant_count);
   S_add_roots(pcb, &libcafe_constant_count);
   libcafe_entry(pcb);
   S_check_roots(pcb, &libcafe_constant_count);
   S_add_roots(pcb, &libtrace_constant_count);
   libtrace_entry(pcb);
   S_check_roots(pcb, &libtrace_constant_count);
   S_add_roots(pcb, &libposix_constant_count);
   libposix_entry(pcb);
   S_check_roots(pcb, &libposix_constant_count);
   libcxr_entry(pcb);
   libtoplevel_entry(pcb);
   return scheme_entry(pcb);
}
